### PR TITLE
Update ReadMe.fa.md for using iran.dat in server

### PR DESCRIPTION
**Pull request by emranovin**
Add tutorial for how to use routing in v2ray server

### CODE REVIEW

**Comment by ahbanavi** [comment]
Thanks, would you please update English README too?

**Comment by ahbanavi** [comment]
Upon further consideration, it seems unnecessary to provide an English version of this. In my view, filtering URLs on the server side could potentially harm users who access websites that log their IP addresses (since all users share the same IP in this case).  
As a best practice, it may be more effective to implement filtering on the client side only.  
I will leave this PR open for a couple of days to hear the thoughts and opinions of others.

**Comment by ahbanavi** [comment]
> @ahbanavi The same thing could be said about VPNs.

Direct access w/o filtering is not the same as using a filtered list that's not transparent to users, and also domestic websites are totally different from foreign ones, almost all of the domestic websites that logging users IPs are Iran-accessed, so it's not the same and weather is a URL is bypassed or not should be a user decision.

**Comment by emranovin** [comment]
You're right @ahbanavi but it's just a tutorial. We are not at the position to make a decision for user. Maybe someone had his own server and want to use the benefit of this repo.
It's up to admin to tell his users about the routing matter.

**Comment by ahbanavi** [comment]
@emranovin fair enough, if you could, please put a warning there or even just mention this PR to let users know the caveats.

**Comment by emranovin** [comment]
@ahbanavi Done.

**Comment by ahbanavi** [comment]
> @ahbanavi Done.

Thx

**Pull request merged**
